name: Create LaTeX PDF

on:
    push:
      branches: 
        - main 

jobs:
    Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Compile
              uses: xu-cheng/latex-action@v2
              with:
                working_directory: ./paper
                root_file: paper.tex

            - name: Generate release tag
              run: echo "release_tag=Build_$(date +"%Y.%m.%d_%Hh%Mmin")" >> "$GITHUB_ENV"

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                working_directory: ./paper
                files: paper.pdf
                tag_name: ${{ env.release_tag }}              
              if: ${{ github.ref == 'refs/heads/main' }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
